version: '3'
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-3000}:3000"
    stdin_open: true
    tty: true
  minio:
    image: minio/minio:edge-cicd
    ports:
      - "${MINIO_API_PORT:-9000}:${MINIO_API_PORT:-9000}"
      - "${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
    environment:
      MINIO_ROOT_USER: ak_eight
      MINIO_ROOT_PASSWORD: sk_eight
    restart: always
    command: server /data --console-address :${MINIO_CONSOLE_PORT:-9001}
volumes:
  mysql:
