name: brakeman
on:
  pull_request:
    paths-ignore:
      - 'public/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get current ruby version from .ruby-version
        id: rbenv
        run: echo "ruby_version=$(cat .ruby-version)" >> $GITHUB_OUTPUT

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rbenv.outputs.ruby_version }}"

      - name: Run brakeman with reviewdog
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          filter_mode: diff_context
          fail_on_error: true
